wandb_version: 1

penalty:
  desc: null
  value: l2
max_iter:
  desc: null
  value: 100
multi_class:
  desc: null
  value: ovr
C:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713720866.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 62
      4: 3.12.0
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
