wandb_version: 1

max_depth:
  desc: null
  value: 30
min_samples_split:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 150
min_samples_leaf:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713721518.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 62
      4: 3.12.0
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
